### ISSUE TITLE
Not compatible with latest beta

### ISSUE THREAD

**Issue by Pastis67** [DewGew/Domoticz-ThinkTheme#11]
Hello it seems not compatible with latest domoticz beta :\  cant figure out why, has someone a clue?

**Comment by waltervl** [comment]
You will have to modify custom.js to change acttheme into the path to thinktheme eg styles/thinktheme (case sensitive)
See also for another theme the following issue:
https://github.com/flatsiedatsie/domoticz-aurora-theme/issues/75

**Comment by YepYip** [comment]
It is not enough, here is all modifications to perform :

- in custom.js : replace "acttheme" with "styles/ThinkTheme"
- in custom.css : replace "@import url("../css/legacy.css");" with "@import url("../../css/legacy.css");"
- in custom.css : replace "background-image: url('../images/searchicon.png');" with "background-image: url('./images/searchicon.png');"

fully functional like this

**Comment by Pastis67** [comment]
Thank you :D work with latest stable version 2022.1 :)
