### ISSUE TITLE
Broken color picker

### ISSUE THREAD

**Issue by Failure404** [DewGew/Domoticz-ThinkTheme#2]
Hi and thanks alot for your work. ThinkTheme is still my favourite theme.
They recently introduced a new color picker for LEDs which looks kind of broken.

![Color Picker](https://beachcom.org/picker.jpg)

Maybe you can do something about this?

**Comment by Failure404** [comment]
I just figured out that this is caused by my Chrome browser's zoom setting.
Domoticz is always zoomed to 110% which breaks the color picker. Zoom 100% and the picker is ok. Then I can zoom to 110% and the picker is still ok. But when zoom is set to 110% before the picker is opened, it breaks.

**Comment by DewGew** [comment]
Seems to be fixed
