### ISSUE TITLE
V2 troubles

### ISSUE THREAD

**Issue by gajotnt** [DewGew/Domoticz-ThinkTheme#3]
Stoped working correctly on InternetExplorer (i know... i know... lol) and also on Chrome and Firefox the fonts...just got worse looking and not centered on the titles of the tiles, really prefered the old style.

Chrome
![chrome](https://user-images.githubusercontent.com/25504364/48661524-98706f00-ea62-11e8-8343-0ab0770716ad.png)
Firefox
![firefox](https://user-images.githubusercontent.com/25504364/48661525-99090580-ea62-11e8-9742-ace347802c97.png)

Also the "LOG", "EDIT" and "notifications" buttons got worst looking also
![screenshot 2018-11-17 12 18 24](https://user-images.githubusercontent.com/25504364/48661545-f3a26180-ea62-11e8-9a18-e46b9817822d.png)

**V1 Fonts were better looking and verticly centered on the tiles**
![v1](https://user-images.githubusercontent.com/25504364/48661526-99090580-ea62-11e8-8ded-3aa58fc6a672.jpg)

**Comment by DewGew** [comment]
Thank you for your feedback 👍
I  changed back the small buttons.
I dont have the same issue like you have on the fonts.. 

![thinktheme](https://user-images.githubusercontent.com/28799807/48828959-5fd9d980-ed71-11e8-81ec-64796007cb53.png)

**Comment by gajotnt** [comment]
indeed your text is more centered than what i was seeing, wierd. Did the whole clean app cache and all.
But still this way of using the font, it looks kinda wierd and not playing well with the whole look of the style, the other was smoother and just didnt feel like it was "photoshoped" in.
Just my 2 cents, keep up the great work :)

![untitled-1](https://user-images.githubusercontent.com/25504364/48834773-1b990a00-ed6e-11e8-9402-5b5664481b08.png)

**Comment by DewGew** [comment]
Maybe I get rid of bold fon in device name. Does that look better??

**Comment by gajotnt** [comment]
Later when i get home from work will update the theme and will give feedback :)

**Comment by gajotnt** [comment]
Indeed it does look better not being bold, but i still prefer the fonts you used before from google api
But thats my taste, keep up the great work, really appreciate it
```
@import url(https://fonts.googleapis.com/css?family=Damion);
@import url(https://fonts.googleapis.com/css?family=Ubuntu);
@import url(https://fonts.googleapis.com/css?family=Roboto:400,500);
@import url(https://fonts.googleapis.com/css?family=Arimo);
@import url(https://fonts.googleapis.com/css?family=Droid+Sans+Mono);
```

**Comment by DewGew** [comment]
Check latest, i think now its quite good design.

**Comment by gajotnt** [comment]
So clean :D awesome 

![94f](https://user-images.githubusercontent.com/25504364/48920565-1aa8cb00-ee89-11e8-8057-c016abf7a459.png)

**Comment by DewGew** [comment]
Great :)
