### ISSUE TITLE
Invalid date after a few seconds

### ISSUE THREAD

**Issue by gillesmartinit** [DewGew/Domoticz-ThinkTheme#6]
I got a "invalid date" behind each device after a few seconds after loading domoticz on my browser (tested with Safari and Chrome)
Look at the picture behind
This is what I have just after loading Domoticz homepage
<img width="381" alt="good date" src="https://user-images.githubusercontent.com/4236800/68082720-49ad1800-fe20-11e9-8126-366c8060e901.png">
then after about 5 seconds
<img width="382" alt="invalid date" src="https://user-images.githubusercontent.com/4236800/68082722-4ca80880-fe20-11e9-8247-2407557fb632.png">
I use last version 2.4.4 with french language

**Comment by Pastis67** [comment]
yup same problem here.. :]

**Comment by DewGew** [comment]
Domoticz change to websocket. I need to figure out how to change js to make it work again.

**Comment by gillesmartinit** [comment]
> Domoticz change to websocket. I need to figure out how to change js to make it work again.

FYI I revert to 2.4.2 and it works

**Comment by DewGew** [comment]
Try beta out beta branch. Seem to work for me. I use domoticz v4.11468.

**Comment by DewGew** [comment]
Is this issue still up?

**Comment by gillesmartinit** [comment]
Sorry for the delay
I use beta branch and now I have a new message

<img width="314" alt="image" src="https://user-images.githubusercontent.com/4236800/69373548-5779ee80-0ca4-11ea-960b-57b4c7e917d2.png">

So I can't check because I'm using stable version 4.10717
The original date format (eg 2019-11-21 11:23:15) is displayed and I don't see "5 min ago" nor "idx number" ( nor "invalid date" :D )

<img width="370" alt="image" src="https://user-images.githubusercontent.com/4236800/69374200-de7b9680-0ca5-11ea-8853-73dd0614a19c.png">

**Comment by DewGew** [comment]
I update master så try that first

**Comment by gillesmartinit** [comment]
> I updated master so try that first

It works with master branch !
Thanks

**Comment by Pastis67** [comment]
thanks
