### ISSUE TITLE
[Python Plugin] Domoticz Theme Manager

### ISSUE THREAD

**Issue by galadril** [DewGew/Domoticz-ThinkTheme#7]
Hi

I just wanted to let you know, that people can install and auto update this theme in Domoticz via the Domoticz Theme Manager (Python plugin)
https://github.com/galadril/domoticz-theme-manager

Can you maybe add this info to the Readme??

Mark

**Comment by DewGew** [comment]
Thanks added to readme

**Comment by galadril** [comment]
Thanks

Op do 20 aug. 2020 om 09:16 schreef DewGew <notifications@github.com>:
